### ISSUE TITLE
Update schema and query runner to allow for multiple associated inputs and outputs

### ISSUE THREAD

**Issue by dosumis** [hubmapconsortium/ccf_owl_query_tester#13]
e.g. 

```YAML

tests: [
   input: 
     locations:
        - http://purl.obolibrary.org/obo/UBERON_0002113
      markers:
        - http://identifiers.org/hgnc/4172
   expected_result:
      cell:
        - http://purl.obolibrary.org/obo/CL_1000716
        - http://purl.obolibrary.org/obo/CL_1000454
        - http://purl.obolibrary.org/obo/CL_1000768
        - http://purl.obolibrary.org/obo/CL_4030019
    ,
   input: 
     locations:
      ...
  ]
```
